// Textos legales FIJOS del descargo de responsabilidad. Son idénticos en todos los informes,
// así que NO los genera la IA: se inyectan en el servidor tras recibir la respuesta.
// Beneficio: byte a byte idénticos siempre + menos tokens (entrada y salida).

export const DESCARGO_INDIVIDUAL =
  'El presente informe ha sido elaborado conforme al Método Podium™, un sistema de valoración clínica propio de la fisioterapia orientado a la evaluación del dolor, el movimiento, la capacidad y la función desde un enfoque clínico-funcional y biopsicosocial. La redacción de este documento ha sido asistida por un sistema de inteligencia artificial (Anthropic Claude, vía API) como herramienta de soporte, y ha sido íntegramente revisado, editado y aprobado por un fisioterapeuta colegiado antes de su emisión. El proveedor de IA no almacena ni reutiliza los datos del paciente. Este documento no constituye un diagnóstico médico, no sustituye la valoración realizada por un facultativo médico y no debe interpretarse como informe pericial ni como prueba válida en procedimientos judiciales, administrativos, aseguradores o legales. La información y los datos objetivos recogidos tienen como finalidad guiar el proceso terapéutico, apoyar la toma de decisiones clínicas en fisioterapia y facilitar la comprensión del estado funcional del paciente en el momento de la valoración. Cualquier uso fuera del ámbito asistencial para el que ha sido diseñado queda expresamente desaconsejado.'

export const DESCARGO_TEAM =
  'El presente informe ha sido elaborado conforme a la Metodología Podium®, un sistema de valoración funcional orientado al rendimiento y la prevención de lesiones en el deporte. La redacción ha sido asistida por un sistema de inteligencia artificial (Anthropic Claude, vía API) y ha sido revisada y aprobada por un fisioterapeuta colegiado antes de su emisión. No constituye un diagnóstico médico ni sustituye la valoración de otros profesionales sanitarios. Los resultados representan una fotografía del momento actual y deben interpretarse junto con la evolución del entrenamiento.'

export const DESCARGO_CAMPAIGN =
  'El presente informe de estudio ha sido elaborado conforme al Método Podium™, agregando las valoraciones individuales de los jugadores incluidos. Su redacción ha sido asistida por un sistema de inteligencia artificial (Anthropic Claude, vía API) como herramienta de soporte, y ha sido íntegramente revisado, editado y aprobado por un fisioterapeuta colegiado antes de su emisión. El proveedor de IA no almacena ni reutiliza los datos. Este documento no constituye un diagnóstico médico, no sustituye la valoración individual de cada jugador ni la valoración de un facultativo médico, y no debe interpretarse como informe pericial ni prueba en procedimientos judiciales, administrativos, aseguradores o legales. Su finalidad es orientar el trabajo colectivo y el seguimiento del grupo en el ámbito asistencial para el que ha sido diseñado.'
